Added new test cases for the algorithms library
m4rs-mt/ILGPU.Algorithms pull request #30
Opened 2020-06-26 13:11 UTC by albosc

Added tests for the high-level functions Scan, Reduce, Transform etc.

2020-07-12 01:13 UTC, MoFtZ requested changes
ISSUE: hi @albosc, I'm getting a number of unit tests failures. Could you please take a look?

- [ ] `ScanExclusiveMaxConstTest` when start = -1 and stepSize = 0.
- [ ] `ScanExclusiveMinConstTest` when start = 1 and stepSize = 0.

On CPU accelerator, the tests fail for any length > 1.
On CUDA accelerator, some pass and some fail.
These failures apply to all data types.

2020-07-12 01:13 UTC, MoFtZ commented on Src/ILGPU.Algorithms.Tests/InitializeTests.cs
> +﻿using System.Linq;
MINOR: `using` statements should be sorted alphabetically.

2020-07-12 01:13 UTC, MoFtZ commented on Src/ILGPU.Algorithms.Tests/VectorTests.cs
> +﻿using System.Numerics;
MINOR: `using` statements should be sorted alphabetically.

2020-07-12 08:10 UTC, albosc commented
Hi @MoFtZ, thank you for the review, but when I run the ScanExclusiveMaxConstTest or ScanExclusiveMinConstTest then I get an output that looks like 0, -1, -1, -1, 0, -1, -1, -1, 0, -1, ... and so on (for ScanExclusiveMaxConstTest). This tests cover the case that an input buffer contains the same values n-times, -1 for the MaxTest. Max or Min returns the same value back for each pair, so the output must look the same as the input ( -1, -1, -1, ... )and since it is an exclusive scan, I shift every value from position n to position n+1, discard n and set the first value to 0 ( 0, -1, -1, -1, ...). As far as I understood the problem, I would say something is broken and that the failed test is appropriated. This was the case for the  CPU accelerator. Right now I do not have access to a CUDA accelerator and can not give you a statement about these tests.
The using statements should be in the right order with the next commit/push.

2020-07-12 10:55 UTC, MoFtZ commented
Thanks @albosc. I'll have a closer look at the implementation of the Scan kernels.

2020-07-25 21:57 UTC, MoFtZ commented
@m4rs-mt If you have time, could you take a look at the Scan kernels? thanks.

2020-07-26 01:37 UTC, MoFtZ approved these changes

2020-07-27 07:37 UTC, MoFtZ requested changes
ISSUE: Your last commit to fix the styles seems to have accidentally moved ILGPU from `57ecc25` to an old commit `2ae313e`. Could you please undo this change? Thanks.

MINOR: In `Src\ILGPU.Algorithms.Tests\ILGPU.Algorithms.Tests.csproj`, the conflict merging seems to have introduced tab characters instead of 4 spaces. Could you please fix these up.

2020-07-27 09:42 UTC, MoFtZ approved these changes

2020-07-27 09:47 UTC, MoFtZ commented
Looks good @albosc. Just need to take it out of draft mode.

2020-07-28 19:19 UTC, m4rs-mt requested changes

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/ArrayExtensionTests.tt
> +
nit: remove empty line

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/ArrayExtensionTests.tt
> +            Assert.Equal(value, actual);
nit: the code above uses empty lines between `actual` and the `Assert...` code. Is this intended?

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/Generic/AlgorithmsTestData.tt
> +        public <#= type.Type #>[] ComputeInvertedSequence(
nit: please add empty lines here to separate the methods.

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/Generic/AlgorithmsTestData.tt
> +}
nit: please remove the newline character at the end of the file to avoid build issues on other OS platforms

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/RadixSortExtensionTests.tt
> +
nit: empty line

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/RadixSortExtensionTests.tt
> +            if (order == "Ascending") {
comment: this is totally fine 🤓 maybe we should change this to use an enumeration or global constants in the future

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/ReorderExtensionTests.tt
> +#pragma warning restore xUnit1026 // Theory methods should use all of their parameters
nit: please remove the newline character here

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/TransformerExtensionTests.tt
> +#pragma warning restore xUnit1026 // Theory methods should use all of their parameters
nit: newline character

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/VectorTests.cs
> +            Vector2 IVector<Vector2>.GetVector() => Vector2.Zero;
question: is there any particular reason why we have to use an explicit interface implementation here?

2020-07-28 19:19 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/WarpExtensionTests.tt
> +#pragma warning restore xUnit1026 // Theory methods should use all of their parameters
nit: newline character

2020-07-28 19:19 UTC, m4rs-mt commented
@albosc Awesome work 🚀 After addressing some minor issues this should be good to go.

2020-07-28 20:58 UTC, albosc commented
@m4rs-mt Thank you for the review. I hope I could address the named issues with the latest commit.

2020-07-30 04:25 UTC, m4rs-mt commented on Src/ILGPU.Algorithms.Tests/Generic/AlgorithmsTestData.tt
> +        Vector2 IVector<Vector2>.GetVector() => Vector2.Zero;
Question: can we make these implementation `public` instead of an explicit interface implementation?

2020-07-30 04:26 UTC, m4rs-mt approved these changes

2020-07-30 08:32 UTC, merged